"""Wallclock measurement harness for Sanctum's five evidence-family tool calls.

Usage (CLI)::

    python -m scripts.measure_wallclock \\
        --corpus tests/fixtures/accuracy_corpus \\
        --n-runs 5

Produces a JSON report on stdout::

    {
      "C1-serial":   {"wallclock_ms": 42.1, "evidence_mb": 0.01, "ms_per_mb": 4210.0},
      "C2-parallel": {"wallclock_ms": 11.3, "evidence_mb": 0.01, "ms_per_mb": 1130.0}
    }

The chart at ``docs/figures/pareto.png`` is generated by ``scripts/plot_pareto.py``
from this output.

Regeneration command (run after Phase 5 ships the F4 demoter)::

    python -m scripts.measure_wallclock \\
        --corpus tests/fixtures/accuracy_corpus --n-runs 5 > reports/wallclock.json
    python -m scripts.plot_pareto reports/wallclock.json \\
        --out docs/figures/pareto.png

Methodology notes
-----------------
*Per-MB normalization* is the load-bearing metric, not absolute milliseconds.
``evidence_mb`` is read from ``corpus_manifest.json`` (a declared constant), NOT
computed from on-disk stub file sizes. This design choice is intentional:
fixture-size manipulation — writing tiny stub files to produce a low absolute
ms number — cannot affect the ``ms_per_mb`` headline if the denominator is
declared in the manifest and not derived from byte counts. See
``docs/ACCURACY.md`` §"Fixture-size manipulation" for the full rationale.
"""

from __future__ import annotations

import asyncio
import contextlib
import json
import os
import secrets
import statistics
import tempfile
import time
from collections.abc import Iterator
from dataclasses import asdict, dataclass
from pathlib import Path


@dataclass
class RunMetrics:
    """Wallclock measurement result for one configuration."""

    config_name: str
    wallclock_ms: float
    evidence_mb: float
    ms_per_mb: float
    tus_m: float | None = None


@contextlib.contextmanager
def _patch_env(overrides: dict[str, str]) -> Iterator[None]:
    """Temporarily override os.environ, restoring previous values on exit."""
    old: dict[str, str | None] = {}
    for k, v in overrides.items():
        old[k] = os.environ.get(k)
        os.environ[k] = v
    try:
        yield
    finally:
        for k, prev in old.items():
            if prev is None:
                os.environ.pop(k, None)
            else:
                os.environ[k] = prev


async def _run_all_tools(case_name: str) -> None:
    """Run all five get_* tool calls once and await their completion."""
    from sanctum import server

    await asyncio.gather(
        server.get_amcache(case_name),
        server.get_bam(case_name),
        server.get_userassist(case_name),
        server.get_prefetch(case_name),
        server.get_sysmon_4688(case_name),
    )


def measure_run(corpus_dir: Path, parallel: bool, n_runs: int = 3) -> RunMetrics:
    """Measure wallclock time for all five tool calls against the accuracy corpus.

    Args:
        corpus_dir: Path to corpus root containing ``corpus_manifest.json``
                    and ``cases/<case_name>/``.
        parallel:   True → ``SANCTUM_PARALLEL_TOOLS=1``; False → ``=0``.
        n_runs:     Number of timed repetitions; median is reported.

    Returns:
        RunMetrics with ``ms_per_mb = wallclock_ms / evidence_mb``.

    Raises:
        ValueError: if ``corpus_manifest.json`` declares ``evidence_mb <= 0``.
        FileNotFoundError: if ``corpus_manifest.json`` is absent.
    """
    from sanctum import server

    manifest_path = corpus_dir / "corpus_manifest.json"
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    evidence_mb = float(manifest["evidence_mb"])
    if evidence_mb <= 0:
        raise ValueError(
            f"corpus_manifest.json evidence_mb must be > 0, got {evidence_mb!r}"
        )
    case_name = manifest.get("case_name", "smoke")
    cases_root = corpus_dir / "cases"

    config_name = "C2-parallel" if parallel else "C1-serial"
    times: list[float] = []

    for _ in range(n_runs):
        with tempfile.TemporaryDirectory() as tmpdir:
            ledger_path = Path(tmpdir) / "ledger.jsonl"
            hmac_key = secrets.token_hex(32)

            env_patch = {
                "SANCTUM_CASES_ROOT": str(cases_root),
                "SANCTUM_OUTPUT_ROOT": tmpdir,
                "SANCTUM_LEDGER_PATH": str(ledger_path),
                "SANCTUM_LEDGER_HMAC_KEY": hmac_key,
                "SANCTUM_PARALLEL_TOOLS": "1" if parallel else "0",
                "SANCTUM_USE_FIXTURE_SIDECAR": "1",
                "SANCTUM_SKIP_MOUNT_CHECK": "1",
            }

            with _patch_env(env_patch):
                server._get_tool_semaphore.cache_clear()
                server._ledger_write_lock = asyncio.Lock()

                t0 = time.perf_counter()
                asyncio.run(_run_all_tools(case_name))
                elapsed_ms = (time.perf_counter() - t0) * 1000.0

            times.append(elapsed_ms)

    wallclock_ms = statistics.median(times)
    ms_per_mb = wallclock_ms / evidence_mb
    return RunMetrics(
        config_name=config_name,
        wallclock_ms=wallclock_ms,
        evidence_mb=evidence_mb,
        ms_per_mb=ms_per_mb,
        tus_m=None,
    )


def _main() -> None:
    import argparse

    parser = argparse.ArgumentParser(
        description="Measure Sanctum wallclock performance against an accuracy corpus.",
    )
    parser.add_argument(
        "--corpus",
        type=Path,
        default=Path("tests/fixtures/accuracy_corpus"),
        help="Path to corpus directory containing corpus_manifest.json",
    )
    parser.add_argument(
        "--n-runs",
        type=int,
        default=5,
        help="Number of timed repetitions per configuration (default: 5)",
    )
    args = parser.parse_args()

    corpus_dir: Path = args.corpus.resolve()
    n_runs: int = args.n_runs

    import sys

    results: dict[str, dict] = {}
    for parallel, label in [(False, "C1-serial"), (True, "C2-parallel")]:
        print(f"Running {label} (n={n_runs})...", file=sys.stderr, flush=True)
        metrics = measure_run(corpus_dir, parallel=parallel, n_runs=n_runs)
        row = asdict(metrics)
        results[label] = row
        print(
            f"  wallclock_ms={metrics.wallclock_ms:.1f}  "
            f"evidence_mb={metrics.evidence_mb}  "
            f"ms_per_mb={metrics.ms_per_mb:.1f}",
            file=sys.stderr,
        )

    print(json.dumps(results, indent=2))


if __name__ == "__main__":
    _main()
